apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: 100M
    ingress.kubernetes.io/app-root: "/"
spec:
  rules:
  - host: app.letsdevops.tk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name:  rollouts-demo
            port:
              number: 80
  - host: preview-app.letsdevops.tk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: rollouts-demo-preview
            port:
              number: 80
